# Generated by Django 4.0.6 on 2022-07-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.IntegerField()),
            ],
        ),
    ]
