# Generated by Django 4.0.6 on 2022-07-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_ingredientsinstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='cost_price',
        ),
    ]
