# Generated by Django 4.0.6 on 2022-07-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_remove_ingredients_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='bakery_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin_App.bakery_item'),
            preserve_default=False,
        ),
    ]
