# Generated by Django 4.0.6 on 2022-07-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_alter_ingredients_bakery_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_item',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bakery_item',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
