# Generated by Django 4.0.6 on 2022-07-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_bakery_item_quantity_alter_bakery_item_profit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='IngredientsRequiredForItem',
        ),
    ]
