# Generated by Django 4.0.6 on 2022-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_rename_ingredients_ingredientsrequiredforitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrequiredforitem',
            name='bakery_item',
            field=models.CharField(max_length=25),
        ),
    ]
