# Generated by Django 4.0.6 on 2022-07-25 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0007_alter_ingredientsrequiredforitem_bakery_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrequiredforitem',
            name='bakery_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.bakery_item'),
        ),
        migrations.AlterField(
            model_name='ingredientsrequiredforitem',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.ingredientsinstock'),
        ),
    ]
