# Generated by Django 4.0.6 on 2022-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0008_alter_ingredientsrequiredforitem_bakery_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrequiredforitem',
            name='bakery_item',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ingredientsrequiredforitem',
            name='ingredients',
            field=models.CharField(max_length=25),
        ),
    ]
