# Generated by Django 4.0.6 on 2022-07-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_bakery_item_quantity_alter_bakery_item_profit'),
        ('customer_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_an_order_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.bakery_item')),
            ],
        ),
        migrations.RenameModel(
            old_name='LoginUser',
            new_name='LoginModel',
        ),
        migrations.DeleteModel(
            name='SignupUser',
        ),
    ]
