# Generated by Django 4.0.6 on 2022-07-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_App', '0002_place_an_order_model_rename_loginuser_loginmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_an_order_model',
            name='sellingPrice',
            field=models.IntegerField(default=0),
        ),
    ]
