# Generated by Django 4.0.6 on 2022-07-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_App', '0003_place_an_order_model_sellingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place_an_order_model',
            old_name='sellingPrice',
            new_name='user',
        ),
    ]
