# Generated by Django 4.0.6 on 2022-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_App', '0006_alter_place_an_order_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_an_order_model',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
