version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/BakeryApp DRF/
    entrypoint:
      - /bin/bash
      - -c
      - python manage.py runserver 0.0.0.0:8000

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
    networks:
      zenatix-docker:
        ipv4_address: 172.18.0.3
    ports:
      - "8000:8000"

    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      zenatix-docker:
        ipv4_address: 172.18.0.2

volumes:
    postgres_data:
      external: True

networks:
  zenatix-docker:
    external:
      name: zenatix-docker

